// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package g

import (
	"github.com/dromara/carbon/v2"
	"github.com/lieywe/msghub/internal/model"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Account = struct {
	ID         field.Number[uint64]
	Platform   field.String
	Name       field.String
	Avatar     field.String
	PlatformID field.String
	Config     field.Struct[model.PlatformConfig]
	LastSyncAt field.Field[*carbon.Carbon]
	CreatedAt  field.Struct[carbon.Carbon]
	UpdatedAt  field.Struct[carbon.Carbon]
	DeletedAt  field.Field[gorm.DeletedAt]
}{
	ID:         field.Number[uint64]{}.WithColumn("id"),
	Platform:   field.String{}.WithColumn("platform"),
	Name:       field.String{}.WithColumn("name"),
	Avatar:     field.String{}.WithColumn("avatar"),
	PlatformID: field.String{}.WithColumn("platform_id"),
	Config:     field.Struct[model.PlatformConfig]{}.WithName("Config"),
	LastSyncAt: field.Field[*carbon.Carbon]{}.WithColumn("last_sync_at"),
	CreatedAt:  field.Struct[carbon.Carbon]{}.WithName("CreatedAt"),
	UpdatedAt:  field.Struct[carbon.Carbon]{}.WithName("UpdatedAt"),
	DeletedAt:  field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}

var PlatformConfig = struct {
	V2ex field.Struct[model.V2exConfig]
}{
	V2ex: field.Struct[model.V2exConfig]{}.WithName("V2ex"),
}

var V2exConfig = struct {
	PersonalAccessToken field.String
}{
	PersonalAccessToken: field.String{}.WithColumn("personal_access_token"),
}
