// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package g

import (
	"github.com/dromara/carbon/v2"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Member = struct {
	ID               field.Number[uint64]
	AccountID        field.Number[uint64]
	Platform         field.String
	PlatformMemberId field.String
	Name             field.String
	Avatar           field.String
	CreatedAt        field.Struct[carbon.Carbon]
	UpdatedAt        field.Struct[carbon.Carbon]
	DeletedAt        field.Field[gorm.DeletedAt]
}{
	ID:               field.Number[uint64]{}.WithColumn("id"),
	AccountID:        field.Number[uint64]{}.WithColumn("account_id"),
	Platform:         field.String{}.WithColumn("platform"),
	PlatformMemberId: field.String{}.WithColumn("platform_member_id"),
	Name:             field.String{}.WithColumn("name"),
	Avatar:           field.String{}.WithColumn("avatar"),
	CreatedAt:        field.Struct[carbon.Carbon]{}.WithName("CreatedAt"),
	UpdatedAt:        field.Struct[carbon.Carbon]{}.WithName("UpdatedAt"),
	DeletedAt:        field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
