// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package g

import (
	"github.com/dromara/carbon/v2"
	"github.com/lieywe/msghub/internal/model"
	"gorm.io/cli/gorm/field"
)

var Message = struct {
	ID           field.Number[uint64]
	AccountID    field.Number[uint64]
	Platform     field.String
	FromMemberId field.Number[uint64]
	OriginID     field.String
	Title        field.String
	Content      field.String
	SendAt       field.Field[*carbon.Carbon]
	CreatedAt    field.Struct[carbon.Carbon]
	UpdatedAt    field.Struct[carbon.Carbon]
	Account      field.Struct[model.Account]
	FromMember   field.Struct[model.Member]
}{
	ID:           field.Number[uint64]{}.WithColumn("id"),
	AccountID:    field.Number[uint64]{}.WithColumn("account_id"),
	Platform:     field.String{}.WithColumn("platform"),
	FromMemberId: field.Number[uint64]{}.WithColumn("from_member_id"),
	OriginID:     field.String{}.WithColumn("origin_id"),
	Title:        field.String{}.WithColumn("title"),
	Content:      field.String{}.WithColumn("content"),
	SendAt:       field.Field[*carbon.Carbon]{}.WithColumn("send_at"),
	CreatedAt:    field.Struct[carbon.Carbon]{}.WithName("CreatedAt"),
	UpdatedAt:    field.Struct[carbon.Carbon]{}.WithName("UpdatedAt"),
	Account:      field.Struct[model.Account]{}.WithName("Account"),
	FromMember:   field.Struct[model.Member]{}.WithName("FromMember"),
}
