/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconAntDesignDingtalkCircleFilled: typeof import('~icons/ant-design/dingtalk-circle-filled.jsx').default
  const IconIonLogoWechat: typeof import('~icons/ion/logo-wechat.jsx').default
  const IconLogosDingtalk: typeof import('~icons/logos/dingtalk.jsx').default
  const IconLogosFacebook: typeof import('~icons/logos/facebook.jsx').default
  const IconLogosTelegram: typeof import('~icons/logos/telegram.jsx').default
  const IconLucideEllipsisVertical: typeof import('~icons/lucide/ellipsis-vertical.jsx').default
  const IconLucideLayoutGrid: typeof import('~icons/lucide/layout-grid.jsx').default
  const IconLucideMessageSquare: typeof import('~icons/lucide/message-square.jsx').default
  const IconLucidePaperclip: typeof import('~icons/lucide/paperclip.jsx').default
  const IconLucidePlus: typeof import('~icons/lucide/plus.jsx').default
  const IconLucideSearch: typeof import('~icons/lucide/search.jsx').default
  const IconLucideSend: typeof import('~icons/lucide/send.jsx').default
  const IconLucideSettings: typeof import('~icons/lucide/settings.jsx').default
  const IconLucideTag: typeof import('~icons/lucide/tag.jsx').default
  const IconLucideTrash2: typeof import('~icons/lucide/trash2.jsx').default
  const IconLucideUsers: typeof import('~icons/lucide/users.jsx').default
  const IconSimpleIconsV2ex: typeof import('~icons/simple-icons/v2ex.jsx').default
  const IconSimpleLogoV2ex: typeof import('~icons/si/mple-logo-v2ex.jsx').default
  const IconSimpleLogosV2ex: typeof import('~icons/si/mple-logos-v2ex.jsx').default
}
